TRAIN:
    model: hrnet_ibna_big
    workers: 3
    batch_size: 256
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.0001

    using_moving_average : True
    last_gamma : True
    using_bn: True

    print_freq: 100
    model_dir: checkpoint/hr_ibn

    train_root: /home/nfs/kaiyang.zhou/data/imagenet/train256x256/
    train_source: /home/nfs/kaiyang.zhou/data/imagenet/train.txt
    val_root: /home/nfs/kaiyang.zhou/data/imagenet/val256x256/
    val_source: /home/nfs/kaiyang.zhou/data/imagenet/val.txt

TEST:
    checkpoint_path : checkpoints/
